# Generated by Django 6.0.1 on 2026-02-17 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("color", models.CharField(default="#3b82f6", max_length=20)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cached_post_count", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner Ad"),
                            ("sponsored_post", "Sponsored Post"),
                            ("sidebar", "Sidebar Ad"),
                            ("in_feed", "In-Feed Ad"),
                        ],
                        default="banner",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="ads/")),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("target_url", models.URLField(max_length=1000)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "cost_per_impression",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_per_click",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("target_locations", models.CharField(blank=True, max_length=500)),
                ("target_keywords", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("max_clicks", models.IntegerField(default=0)),
                ("max_impressions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_categories",
                    models.ManyToManyField(
                        blank=True, related_name="advertisements", to="core.category"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment_images/"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can join"),
                            ("private", "Private - Approval required"),
                            ("secret", "Secret - Invitation only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("allow_member_posts", models.BooleanField(default=True)),
                ("require_post_approval", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="groups/covers/"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="groups/icons/"),
                ),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("post_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="administered_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderated_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("business", "Business"),
                            ("user_news", "User News"),
                            ("news", "Auto-Fetched News"),
                            ("profile_post", "Profile Post"),
                            ("sponsored", "Sponsored Post"),
                        ],
                        default="discussion",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("featured", "Featured"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public - Everyone can view"),
                            (
                                "followers",
                                "Followers Only - Only my followers can view",
                            ),
                            ("private", "Private - Only me"),
                            (
                                "specific",
                                "Specific Followers - Select specific followers",
                            ),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("source_name", models.CharField(blank=True, max_length=200)),
                ("external_source", models.CharField(blank=True, max_length=200)),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("is_auto_fetched", models.BooleanField(default=False)),
                ("original_published_at", models.DateTimeField(blank=True, null=True)),
                ("is_news_submission", models.BooleanField(default=False)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending AI Verification"),
                            ("verified", "Verified"),
                            ("fake", "Fake News"),
                            ("questionable", "Questionable"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verification_score", models.FloatField(default=0.0)),
                ("verification_details", models.JSONField(blank=True, default=dict)),
                (
                    "verification_method",
                    models.CharField(default="manual", max_length=50),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("source_reputation_score", models.FloatField(default=0.0)),
                (
                    "source_trust_level",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("trusted", "Trusted"),
                            ("questionable", "Questionable"),
                            ("untrusted", "Untrusted"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="post_images/"),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("video_urls", models.JSONField(blank=True, default=list, null=True)),
                ("audio_urls", models.JSONField(blank=True, default=list, null=True)),
                ("has_media", models.BooleanField(default=False)),
                ("is_sponsored", models.BooleanField(default=False)),
                ("is_banner", models.BooleanField(default=False)),
                ("profile_only", models.BooleanField(default=False)),
                ("banner_expires_at", models.DateTimeField(blank=True, null=True)),
                ("banner_priority", models.IntegerField(default=0)),
                ("banner_clicks", models.PositiveIntegerField(default=0)),
                ("banner_impressions", models.PositiveIntegerField(default=0)),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_sharing", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("repost_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("last_engagement_update", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("meta_description", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.advertisement",
                    ),
                ),
                (
                    "allowed_viewers",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific followers who can view this post (for privacy="specific")',
                        related_name="can_view_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.category",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_posts",
                        to="core.group",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("mention", "Mention"),
                            ("post", "New Post"),
                            ("reply", "Reply"),
                            ("ad_approval", "Ad Approval"),
                            ("business_verification", "Business Verification"),
                            ("group_invite", "Group Invite"),
                            ("group_post_approved", "Group Post Approved"),
                            ("group_post_rejected", "Group Post Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.comment",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.group",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_posts",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.post",
            ),
        ),
        migrations.CreateModel(
            name="Repost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Optional comment when reposting"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reposts", models.PositiveIntegerField(default=0)),
                (
                    "original_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repost_instances",
                        to="core.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_approve_threshold",
                    models.FloatField(
                        default=0.8,
                        help_text="AI score threshold for auto-approval (0.0-1.0)",
                    ),
                ),
                (
                    "require_manual_review_for_fake",
                    models.BooleanField(
                        default=True,
                        help_text="Require manual review for posts marked as fake",
                    ),
                ),
                ("notify_admin_on_submission", models.BooleanField(default=True)),
                ("notify_user_on_approval", models.BooleanField(default=True)),
                (
                    "trusted_sources",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of trusted news sources",
                    ),
                ),
                (
                    "blocked_sources",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of blocked sources"
                    ),
                ),
                (
                    "auto_verify_news",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically verify news articles using AI",
                    ),
                ),
                (
                    "auto_post_verified_news",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically post verified news to online news page",
                    ),
                ),
                (
                    "auto_delete_fake_news",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically delete/archive news detected as fake",
                    ),
                ),
                (
                    "verification_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Minimum confidence score (0-1) for auto-approval",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "verification_schedule",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("every_6_hours", "Every 6 Hours"),
                            ("every_12_hours", "Every 12 Hours"),
                            ("daily", "Daily"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        help_text="How often to run automatic verification",
                        max_length=20,
                    ),
                ),
                (
                    "max_posts_to_verify",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum number of posts to verify per batch",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "enable_auto_fetch",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically fetch news from RSS feeds",
                    ),
                ),
                (
                    "fetch_schedule",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("every_3_hours", "Every 3 Hours"),
                            ("every_6_hours", "Every 6 Hours"),
                            ("daily", "Daily"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "max_news_per_fetch",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "enable_guest_access",
                    models.BooleanField(
                        default=True,
                        help_text="Allow non-logged-in users to view content",
                    ),
                ),
                (
                    "max_posts_per_day",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum posts per user per day",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "require_post_approval",
                    models.BooleanField(
                        default=True, help_text="Require admin approval for user posts"
                    ),
                ),
                (
                    "max_post_length",
                    models.IntegerField(
                        default=10000,
                        help_text="Maximum characters per post",
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
                (
                    "max_image_size",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum image size in MB",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "allowed_image_types",
                    models.CharField(
                        default="jpg,jpeg,png,gif,webp",
                        help_text="Comma-separated list of allowed image formats",
                        max_length=200,
                    ),
                ),
                (
                    "allow_registrations",
                    models.BooleanField(
                        default=True, help_text="Allow new user registrations"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=False,
                        help_text="Require email verification for new accounts",
                    ),
                ),
                (
                    "default_user_role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("contributor", "Contributor"),
                            ("editor", "Editor"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "max_ads_per_business",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum active ads per business",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "banner_rotation_interval",
                    models.IntegerField(
                        default=30,
                        help_text="Banner rotation interval in seconds",
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                (
                    "ad_approval_required",
                    models.BooleanField(
                        default=True, help_text="Require admin approval for new ads"
                    ),
                ),
                (
                    "min_ad_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Minimum budget per advertisement",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("100.00"))
                        ],
                    ),
                ),
                (
                    "ad_impression_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0010"),
                        help_text="Cost per impression (in NGN)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "ad_click_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0500"),
                        help_text="Cost per click (in NGN)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0100"))
                        ],
                    ),
                ),
                (
                    "allow_group_creation",
                    models.BooleanField(
                        default=True, help_text="Allow users to create groups"
                    ),
                ),
                (
                    "max_groups_per_user",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum groups a user can create",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_members_for_public_group",
                    models.IntegerField(
                        default=10,
                        help_text="Minimum members required to become a public group",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "require_group_approval",
                    models.BooleanField(
                        default=False, help_text="Require admin approval for new groups"
                    ),
                ),
                (
                    "trending_calculation_interval",
                    models.IntegerField(
                        default=6,
                        help_text="Trending calculation interval in hours",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "trending_time_window",
                    models.IntegerField(
                        default=48,
                        help_text="Time window for trending posts in hours",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "engagement_weight_like",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight multiplier for likes in trending calculation",
                    ),
                ),
                (
                    "engagement_weight_comment",
                    models.FloatField(
                        default=2.0,
                        help_text="Weight multiplier for comments in trending calculation",
                    ),
                ),
                (
                    "engagement_weight_share",
                    models.FloatField(
                        default=3.0,
                        help_text="Weight multiplier for shares in trending calculation",
                    ),
                ),
                (
                    "engagement_weight_view",
                    models.FloatField(
                        default=0.01,
                        help_text="Weight multiplier for views in trending calculation",
                    ),
                ),
                (
                    "cache_timeout",
                    models.IntegerField(
                        default=300,
                        help_text="Cache timeout in seconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compress_images",
                    models.BooleanField(
                        default=True, help_text="Automatically compress uploaded images"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="Put site in maintenance mode"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="Site is under maintenance. Please check back soon.",
                    ),
                ),
                (
                    "allow_admin_during_maintenance",
                    models.BooleanField(
                        default=True, help_text="Allow admin access during maintenance"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="Default meta description for SEO"
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, help_text="Default meta keywords for SEO"
                    ),
                ),
                (
                    "robots_txt",
                    models.TextField(
                        blank=True,
                        default="User-agent: *\nDisallow: /admin/\nDisallow: /private/\nAllow: /\nSitemap: /sitemap.xml",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_push_notifications", models.BooleanField(default=False)),
                ("notify_admin_on_new_post", models.BooleanField(default=True)),
                ("notify_admin_on_new_user", models.BooleanField(default=True)),
                ("notify_admin_on_fake_news", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("post_created", "Post Created"),
                            ("comment_created", "Comment Created"),
                            ("post_liked", "Post Liked"),
                            ("post_shared", "Post Shared"),
                            ("post_saved", "Post Saved"),
                            ("post_reposted", "Post Reposted"),
                            ("profile_updated", "Profile Updated"),
                            ("followed_user", "Followed User"),
                            ("ad_submitted", "Ad Submitted"),
                            ("group_created", "Group Created"),
                            ("group_joined", "Group Joined"),
                            ("ad_approved", "Ad Approved"),
                            ("ad_rejected", "Ad Rejected"),
                            ("business_verified", "Business Verified"),
                            ("group_post_created", "Group Post Created"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.post",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Comma separated list of interests"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, max_length=1000)),
                ("instagram_url", models.URLField(blank=True, max_length=1000)),
                ("linkedin_url", models.URLField(blank=True, max_length=1000)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                            ("group", "Group Account"),
                            ("admin", "Admin"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("is_verified_business", models.BooleanField(default=False)),
                (
                    "ad_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("business_registration", models.CharField(blank=True, max_length=100)),
                ("business_address", models.TextField(blank=True)),
                ("business_phone", models.CharField(blank=True, max_length=20)),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("business_website", models.URLField(blank=True, max_length=1000)),
                ("business_verified_at", models.DateTimeField(blank=True, null=True)),
                ("receive_promo_emails", models.BooleanField(default=True)),
                ("ad_notifications", models.BooleanField(default=True)),
                ("is_group_account", models.BooleanField(default=False)),
                ("total_posts", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("total_likes_received", models.PositiveIntegerField(default=0)),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                ("email_notifications", models.BooleanField(default=True)),
                ("show_online_status", models.BooleanField(default=True)),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("friends_only", "Friends Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to="core.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ctr", models.FloatField(default=0)),
                ("cpc", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="core.advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ad Analytics",
                "unique_together": {("advertisement", "date")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_banned", models.BooleanField(default=False)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-published_at"], name="core_post_publish_9131cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="core_post_status_01541c_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_type"], name="core_post_post_ty_46f476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category"], name="core_post_categor_1cadd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_auto_fetched"], name="core_post_is_auto_33315c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_sponsored"], name="core_post_is_spon_9833a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["profile_only"], name="core_post_profile_eda6c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["verification_status"], name="core_post_verific_583e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["submission_status"], name="core_post_submiss_83fbfd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppost",
            unique_together={("group", "post")},
        ),
        migrations.AlterUniqueTogether(
            name="repost",
            unique_together={("user", "original_post")},
        ),
    ]
