# Generated by Django 6.0.1 on 2026-01-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(db_column="comment_count", default=0),
        ),
    ]
