# Generated by Django 6.0.1 on 2026-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post_comments_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
