# Generated by Django 6.0.1 on 2026-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_post_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="target_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="external_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="business_website",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
