# Generated by Django 6.0.1 on 2026-02-12 10:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_advertisement_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ad_click_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0500"),
                help_text="Cost per click (in NGN)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0100"))
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="allow_admin_during_maintenance",
            field=models.BooleanField(
                default=True, help_text="Allow admin access during maintenance"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="allow_registrations",
            field=models.BooleanField(
                default=True, help_text="Allow new user registrations"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="allowed_image_types",
            field=models.CharField(
                default="jpg,jpeg,png,gif,webp",
                help_text="Comma-separated list of allowed image formats",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_post_verified_news",
            field=models.BooleanField(
                default=False,
                help_text="Automatically post verified news to online news page",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="blocked_sources",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of blocked sources"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="cache_timeout",
            field=models.IntegerField(
                default=300,
                help_text="Cache timeout in seconds",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="compress_images",
            field=models.BooleanField(
                default=True, help_text="Automatically compress uploaded images"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_user_role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("contributor", "Contributor"),
                    ("editor", "Editor"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_auto_fetch",
            field=models.BooleanField(
                default=True, help_text="Automatically fetch news from RSS feeds"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_push_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="engagement_weight_comment",
            field=models.FloatField(
                default=2.0,
                help_text="Weight multiplier for comments in trending calculation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="engagement_weight_like",
            field=models.FloatField(
                default=1.0,
                help_text="Weight multiplier for likes in trending calculation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="engagement_weight_share",
            field=models.FloatField(
                default=3.0,
                help_text="Weight multiplier for shares in trending calculation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="engagement_weight_view",
            field=models.FloatField(
                default=0.01,
                help_text="Weight multiplier for views in trending calculation",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="fetch_schedule",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("every_3_hours", "Every 3 Hours"),
                    ("every_6_hours", "Every 6 Hours"),
                    ("daily", "Daily"),
                    ("manual", "Manual Only"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_message",
            field=models.TextField(
                blank=True, default="Site is under maintenance. Please check back soon."
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False, help_text="Put site in maintenance mode"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_image_size",
            field=models.IntegerField(
                default=5,
                help_text="Maximum image size in MB",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_news_per_fetch",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_post_length",
            field=models.IntegerField(
                default=10000,
                help_text="Maximum characters per post",
                validators=[django.core.validators.MinValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_posts_to_verify",
            field=models.IntegerField(
                default=50,
                help_text="Maximum number of posts to verify per batch",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="meta_description",
            field=models.TextField(
                blank=True, help_text="Default meta description for SEO"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="meta_keywords",
            field=models.TextField(
                blank=True, help_text="Default meta keywords for SEO"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_admin_on_fake_news",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_admin_on_new_post",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_admin_on_new_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_email_verification",
            field=models.BooleanField(
                default=False, help_text="Require email verification for new accounts"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_group_approval",
            field=models.BooleanField(
                default=False, help_text="Require admin approval for new groups"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_post_approval",
            field=models.BooleanField(
                default=True, help_text="Require admin approval for user posts"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="robots_txt",
            field=models.TextField(
                blank=True,
                default="User-agent: *\nDisallow: /admin/\nDisallow: /private/\nAllow: /\nSitemap: /sitemap.xml",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="support_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="telegram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="trending_time_window",
            field=models.IntegerField(
                default=48,
                help_text="Time window for trending posts in hours",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="trusted_sources",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of trusted sources (e.g., punchng.com, vanguardngr.com)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_settings_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="verification_schedule",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("every_6_hours", "Every 6 Hours"),
                    ("every_12_hours", "Every 12 Hours"),
                    ("daily", "Daily"),
                    ("manual", "Manual Only"),
                ],
                default="daily",
                help_text="How often to run automatic verification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="ad_approval_required",
            field=models.BooleanField(
                default=True, help_text="Require admin approval for new ads"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="ad_impression_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0010"),
                help_text="Cost per impression (in NGN)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="allow_group_creation",
            field=models.BooleanField(
                default=True, help_text="Allow users to create groups"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="auto_delete_fake_news",
            field=models.BooleanField(
                default=False,
                help_text="Automatically delete/archive news detected as fake",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="auto_verify_news",
            field=models.BooleanField(
                default=True, help_text="Automatically verify news articles using AI"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="banner_rotation_interval",
            field=models.IntegerField(
                default=30,
                help_text="Banner rotation interval in seconds",
                validators=[django.core.validators.MinValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="enable_guest_access",
            field=models.BooleanField(
                default=True, help_text="Allow non-logged-in users to view content"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_ads_per_business",
            field=models.IntegerField(
                default=5,
                help_text="Maximum active ads per business",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_groups_per_user",
            field=models.IntegerField(
                default=5,
                help_text="Maximum groups a user can create",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_posts_per_day",
            field=models.IntegerField(
                default=10,
                help_text="Maximum posts per user per day",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="min_ad_budget",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Minimum budget per advertisement",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("100.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="min_members_for_public_group",
            field=models.IntegerField(
                default=10,
                help_text="Minimum members required to become a public group",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="trending_calculation_interval",
            field=models.IntegerField(
                default=6,
                help_text="Trending calculation interval in hours",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="verification_threshold",
            field=models.FloatField(
                default=0.7,
                help_text="Minimum confidence score (0-1) for auto-approval",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
