# Generated by Django 6.0.1 on 2026-02-12 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemsettings_ad_click_rate_systemsettings_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allowed_viewers",
            field=models.ManyToManyField(
                blank=True,
                help_text='Specific followers who can view this post (for privacy="specific")',
                related_name="can_view_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public - Everyone can view"),
                    ("followers", "Followers Only - Only my followers can view"),
                    ("private", "Private - Only me"),
                    ("specific", "Specific Followers - Select specific followers"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
