# Generated by Django 6.0.1 on 2026-02-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_post_allowed_viewers_post_privacy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ["-created_at"]},
        ),
    ]
