# Generated by Django 6.0.1 on 2026-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_follow_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of audio URLs found in the article",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="has_media",
            field=models.BooleanField(
                default=False, help_text="Whether post contains video/audio"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of video URLs found in the article",
                null=True,
            ),
        ),
    ]
