# Generated by Django 6.0.1 on 2026-02-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_post_audio_urls_post_has_media_post_video_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_news_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="original_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_news",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="source_reputation_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="source_trust_level",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("trusted", "Trusted"),
                    ("questionable", "Questionable"),
                    ("untrusted", "Untrusted"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged for Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="verification_method",
            field=models.CharField(default="manual", max_length=50),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_approve_threshold",
            field=models.FloatField(
                default=0.8, help_text="AI score threshold for auto-approval (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_admin_on_submission",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="notify_user_on_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_manual_review_for_fake",
            field=models.BooleanField(
                default=True, help_text="Require manual review for posts marked as fake"
            ),
        ),
    ]
