# Generated by Django 3.1.1 on 2021-01-25 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_post', models.CharField(max_length=3000)),
                ('post_title', models.CharField(max_length=250, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='picture/')),
                ('video', models.FileField(null=True, upload_to='video/')),
                ('audio', models.FileField(null=True, upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='news_table',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_title', models.CharField(max_length=250, unique=True)),
                ('news_post', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='picture/')),
                ('video', models.FileField(null=True, upload_to='video/')),
                ('audio', models.FileField(null=True, upload_to='audio/')),
                ('post_source', models.CharField(max_length=250, null=True)),
                ('approved', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='likeshare_table',
            fields=[
                ('sharelike_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.comment_table')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_table')),
            ],
        ),
        migrations.AddField(
            model_name='comment_table',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_table'),
        ),
    ]
