# Generated by Django 3.1.1 on 2021-01-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeshare_table',
            name='like',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='share',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='unlike',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='likeshare_table',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.comment_table'),
        ),
        migrations.AlterField(
            model_name='likeshare_table',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_table'),
        ),
    ]
