# Generated by Django 3.1.1 on 2021-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210125_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeshare_table',
            name='like_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='share_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='unlike_num',
            field=models.IntegerField(null=True),
        ),
    ]
