# Generated by Django 3.1.1 on 2021-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20210126_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeshare_table',
            name='like_num',
        ),
        migrations.RemoveField(
            model_name='likeshare_table',
            name='share_num',
        ),
        migrations.RemoveField(
            model_name='likeshare_table',
            name='unlike_num',
        ),
        migrations.AddField(
            model_name='comment_table',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment_table',
            name='unlike_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_table',
            name='share_num',
            field=models.IntegerField(default=0),
        ),
    ]
