# Generated by Django 3.1.1 on 2021-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20210127_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_table',
            name='post_title',
            field=models.CharField(max_length=250),
        ),
    ]
