# Generated by Django 3.1.1 on 2021-02-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userportalapp', '0003_auto_20210128_1216'),
        ('newsapp', '0005_auto_20210127_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_table',
            name='userp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userportalapp.userpost_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='userp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userportalapp.userpost_table'),
        ),
    ]
