# Generated by Django 3.1.1 on 2021-02-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userportalapp', '0003_auto_20210128_1216'),
        ('newsapp', '0006_auto_20210201_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_table',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_table'),
        ),
        migrations.AlterField(
            model_name='comment_table',
            name='userp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userportalapp.userpost_table'),
        ),
    ]
