# Generated by Django 3.1.1 on 2021-02-09 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20210201_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_table',
            old_name='comment_date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='likeshare_table',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
