# Generated by Django 3.1.1 on 2021-01-28 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpost_table',
            fields=[
                ('userp_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', models.CharField(max_length=5000)),
                ('picture', models.ImageField(null=True, upload_to='userpics/')),
                ('video', models.FileField(null=True, upload_to='uservideo/')),
                ('audio', models.FileField(null=True, upload_to='useraudio/')),
                ('share_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
