# Generated by Django 3.1.1 on 2021-02-09 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userportalapp', '0003_auto_20210128_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_table',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
