"""
Django settings for ojukaye project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-i)ef7k5z)av6nsza0zkhaq87$rj55#4)2e@(#a66qbwk8c^2&$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
# DEBUG = False

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'core.middleware.MessageToModalMiddleware',
    # 'ojuaye.context_processors.categories',
    # 'ojuaye.context_processors.trending_posts',
    # 'ojuaye.context_processors.notifications_count',
    'core.middleware.GuestRestrictionMiddleware',
    'core.middleware.BusinessAccountMiddleware',
]

ROOT_URLCONF = "ojukaye.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', 
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_context',

            ],
        },
    },
]

WSGI_APPLICATION = "ojukaye.wsgi.application"




DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ojukaye",
        "USER": "root",
        "PASSWORD": "shot-010907",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "OPTIONS": {
            "autocommit": True,
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Add this to serve media files through WhiteNoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True


# Create required directories on startup
os.makedirs(os.path.join(BASE_DIR, 'static'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'staticfiles'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media/profile_pics'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media/cover_photos'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media/post_images'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media/comment_images'), exist_ok=True)

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Crispy Forms
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# File upload settings
MAX_UPLOAD_SIZE = 10485760  # 10MB
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
ALLOWED_DOCUMENT_EXTENSIONS = ['pdf', 'doc', 'docx', 'txt']

AD_IMPRESSION_RATE = 0.001  # ₦1 per 1000 impressions
MIN_AD_BUDGET = 1000.00  # Minimum ad budget in Naira

# News API Configuration
NEWS_API_KEY = '70faa98e3eb044e88aeb2695a7c2dae8' 
NEWS_SOURCES = [
    'premiumtimesng.com',
    'punchng.com',
    'vanguardngr.com',
    'guardian.ng',
    'thisdaylive.com',
    'sunnewsonline.com',
]
NEWS_FETCH_SETTINGS = {
    'TIMEOUT': 15,
    'MAX_RETRIES': 3,
    'USER_AGENT_ROTATION': True,
    'USE_PROXIES': False,  # Set to True if you have proxies
    'RESPECT_ROBOTS_TXT': True,
    'DELAY_BETWEEN_REQUESTS': 1,
}
ENABLE_NEWS_VERIFICATION = True
AUTO_VERIFY_NEWS = True
AUTO_DELETE_FAKE_NEWS = False
VERIFICATION_THRESHOLD = 0.7

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = 'noreply@ojukaye.com'

# Create required directories on startup


# Site configuration
SITE_NAME = 'Ojukaye'
SITE_DOMAIN = 'ojukaye.com'
SITE_DESCRIPTION = 'Nigeria\'s Modern News & Discussion Platform'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Keep your existing CACHE_TIMEOUTS
CACHE_TIMEOUTS = {
    'banners': 300,  # 5 minutes
    'categories': 3600,  # 1 hour
    'trending_posts': 900,  # 15 minutes
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
        'ad_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'ads.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.signals': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.views': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.models': {
            'handlers': ['ad_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Security settings for production
if not DEBUG:
    # For production only - comment these during development
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ==================== TEMPLATE CACHE FIX ====================
# This ensures templates always load the latest version
TEMPLATES[0]['OPTIONS']['loaders'] = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]
TEMPLATES[0]['APP_DIRS'] = False  # Disable cached loader

# Disable all caching during development
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    
    # Add middleware to disable browser cache
    MIDDLEWARE.insert(0, 'core.middleware.DisableBrowserCacheMiddleware')